language: python
sudo: required

python:
    - "3.6"
  
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - mkdir -p $HOME/tmp
  - export TMPDIR=$HOME/tmp

install:
    - conda create -q -n testenv --yes python=3.6 numpy scipy pandas cython scikit-learn invoke matplotlib
    - source activate testenv
    - conda install -c bioconda samtools openssl=1.0 star pysam 
    - pip install htseq==0.13.5
    - pip install taggd
    - python setup.py build
    - python setup.py install
   
script:
    - python setup.py test
    - python -m unittest testrun.py

after_success:
    - coveralls
  
notifications:
    email: false
